services:
  app:
    build: .
    container_name: amanat_finance_be
    volumes:
      - .:/var/www
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: amanat_finance_api
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: amanat_finance_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: